#!/usr/bin/with-contenv sh

# From https://github.com/smebberson/docker-alpine/tree/master/alpine-apache

# avoid 'already pid is running' error
rm -f /run/apache2/httpd.pid

chmod -R 777 /opt/svnadmin/data

#exec /usr/sbin/apachectl -DFOREGROUND;
exec /usr/sbin/httpd -DFOREGROUND;